from core import USEREVENT

QUIT_EVENT = USEREVENT + 1
PUSH_ARROW_EVENT = USEREVENT + 2
REPEAT_ARROW_EVENT = USEREVENT + 3
PUSH_ACTION_EVENT = USEREVENT + 4
PUSH_ACTION2_EVENT = USEREVENT + 5
REPEAT_ACTION_EVENT = USEREVENT + 6
REPEAT_ACTION2_EVENT = USEREVENT + 7
